[colors.bright]
black = "#565656"
blue = "#8cd0d3"
cyan = "#74fdf3"
green = "#b8e36d"
magenta = "#ac7bf0"
red = "#ff4351"
white = "#ffffff"
yellow = "#ffd952"

[colors.normal]
black = "#1d1f21"
blue = "#008df8"
cyan = "#00d8eb"
green = "#1cdd83"
magenta = "#fc75ff"
red = "#ff000f"
white = "#ffffff"
yellow = "#ffb900"

[colors.primary]
background = "#1e1e2e"
foreground = "#ffffff"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "regular"

[window]
decorations = "none"
opacity = 0.55

[window.padding]
x = 15
y = 15
